### ISSUE TITLE
Numba

### ISSUE THREAD

**Issue by garyrob** [00sapo/cython_list_test#6]
I've done a lot with numba and found it to be a tremendous advantage. I suggest you try to tweak your numba example a bit more. I'd do it myself but I have very little free time right now.  I could look into it later if you really give up. 

If there's really something that makes your example code impractical, then I must say that based on my experience, this isn't a representative example and misrepresents numba's value.

Finally, I'd suggest submitting the problem to the numba team; I would expect them to either fix it or give a solid reason why they don't view it as a problem for the vast majority of use cases.

**Comment by crizCraig** [comment]
You may want to try numpy arrays with numba.

**Comment by smpurkis** [comment]
I've made a pull request with a working Numba implementation #7

**Comment by garyrob** [comment]
Excellent! This issue should now morph to running it under the same conditions as the other tests

**Comment by 00sapo** [comment]
Merged
